version: "3.9"

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: hospitality
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/hospitality
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: hospitality

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - backend

volumes:
  db-data:
